CREATE TABLE IF NOT EXISTS `ruedas` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `semana` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `comentarios` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `L1` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `L2` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `L3` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `L4` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `L5` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `L6` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `M1` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `M2` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `M3` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `M4` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `M5` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `M6` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `X1` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `X2` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `X3` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `X4` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `X5` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `X6` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `J1` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `J2` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `J3` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `J4` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `J5` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `J6` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `V1` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `V2` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `V3` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `V4` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `V5` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `V6` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=8 ;


CREATE TABLE IF NOT EXISTS `tasks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `contenido` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `tipo` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `estado` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `fecha` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=33 ;


CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `apellidos` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `phone` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `contrasena` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `cargo` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `activo` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `avatar` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `cochemarca` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `cochemodelo` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `CT` int(11) NOT NULL,
  `VT` int(11) NOT NULL,
  `ratio` int(11) NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=6 ;
